services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000"]
      interval: 5s
      timeout: 5s
      retries: 5
